language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-23
    
after_success:
 - ./gradlew cobertura coveralls

